# Generated by Django 5.1.3 on 2024-11-12 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название предмета')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название предложения')),
                ('teacher', models.CharField(max_length=100, verbose_name='Название предложения')),
                ('payment', models.CharField(max_length=50, verbose_name='Стоимость')),
                ('description', models.TextField(verbose_name='Описание предложения')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('agency', models.CharField(max_length=80, verbose_name='Агентство')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studywise_app.subject', verbose_name='Выберите предмет')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
