# Generated by Django 5.1.3 on 2024-11-12 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата и время публикации'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='teacher',
            field=models.CharField(max_length=100, verbose_name='Имя преподователя'),
        ),
    ]
