# Generated by Django 5.1.3 on 2024-11-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0003_alter_offer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='experience',
            field=models.CharField(max_length=50, null=True, verbose_name='Опыт'),
        ),
    ]
