# Generated by Django 5.1.3 on 2024-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0004_offer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.CharField(default='Не указано', max_length=50, verbose_name='Опыт'),
        ),
    ]
