# Generated by Django 5.1.3 on 2024-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0005_alter_offer_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='agency',
            field=models.CharField(default='Самозанятый репетитор', max_length=80, verbose_name='Агентство'),
        ),
    ]
