# Generated by Django 5.1.3 on 2024-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0006_alter_offer_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='experience',
            field=models.CharField(default='Без опыта', max_length=50, verbose_name='Опыт'),
        ),
    ]
