# Generated by Django 5.1.3 on 2024-11-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywise_app', '0007_alter_offer_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Предмет')),
            ],
        ),
    ]
